### ISSUE TITLE
build error drm_mode_object_find missing parameter

### ISSUE THREAD

**Issue by alowe7** [displaylink-rpm/displaylink-rpm#56] opened 2018-02-24 20:12 UTC
to reproduce, try to build evdi on for example fedora 27 (4.15.4-300.fc27.x86_64):

```
/usr/src/evdi-1.5.0/evdi_connector.c:90:6: error: too few arguments to function ‘drm_mode_object_find’
```

fix/workaround:

```
	  drm_mode_object_find(connector->dev, NULL, enc_id,
				 DRM_MODE_OBJECT_ENCODER);
```

**Comment by ssaavedra** [comment] 2018-02-24 23:14
Duplicate of #55 see latest comments there for a workaround.

**Closed by ssaavedra** 2018-02-24 23:14 UTC
