### ISSUE TITLE
EVDI-1.13.1 doesn't build for EL 8.7 

### ISSUE THREAD

**Issue by mark-hyde** [displaylink-rpm/displaylink-rpm#242] opened 2023-05-09 14:04 UTC
I was not immediately able to install the latest displaylink-rpm on my Alma8 linux laptop.
I was able to workaround the issue by commenting out some lines in the evdi source code and rebuilding
I have reproduced the issue on a clean almalinux8 Vagrant box:

  * Are you using the latest DisplayLink driver?
      I'm using the latest displaylink-rpm package:

          displaylink-1.13.1-1.x86_64

  * Are you using the latest EVDI module?
        evdi in package is version 1.13.1
        
        /usr/src/evdi-1.13.1

  * Is this issue related to evdi/kernel?
 evdi kernel module will not build without modification

  * If you are having an issue upgrading, have you tried to do a clean install of the driver?
 I am using a fresh libvirt almalinux/8 Vagrant box to reproduce the issue

  * Distro Version:  AlmaLinux release 8.7 (Stone Smilodon)
  * Kernel version:Linux localhost.localdomain 4.18.0-425.19.2.el8_7.x86_64 #1 SMP Tue Apr 4 05:30:47 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux

  * `/var/log/displaylink/displaylink.log`
```
[root@localhost ~]# cat /var/log/displaylink/displaylink.log 
Creating symlink /var/lib/dkms/evdi/1.13.1/source -> /usr/src/evdi-1.13.1
Sign command: /lib/modules/4.18.0-425.19.2.el8_7.x86_64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
Certificate or key are missing, generating self signed certificate for MOK...

Building module:
Cleaning build area...
make -j1 KERNELRELEASE=4.18.0-425.19.2.el8_7.x86_64 all INCLUDEDIR=/lib/modules/4.18.0-425.19.2.el8_7.x86_64/build/include KVERSION=4.18.0-425.19.2.el8_7.x86_64 DKMS_BUILD=1...(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.18.0-425.19.2.el8_7.x86_64 (x86_64)
Consult /var/lib/dkms/evdi/1.13.1/build/make.log for more information.
Sign command: /lib/modules/4.18.0-425.19.2.el8_7.x86_64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module:
Cleaning build area...
make -j1 KERNELRELEASE=4.18.0-425.19.2.el8_7.x86_64 all INCLUDEDIR=/lib/modules/4.18.0-425.19.2.el8_7.x86_64/build/include KVERSION=4.18.0-425.19.2.el8_7.x86_64 DKMS_BUILD=1...(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.18.0-425.19.2.el8_7.x86_64 (x86_64)
Consult /var/lib/dkms/evdi/1.13.1/build/make.log for more information.
```
  
  * `/var/lib/dkms/evdi/kernel-[version]/log/make.log`
```
[root@localhost ~]# cat /var/lib/dkms/evdi/1.13.1/build/make.log 
DKMS make.log for evdi-1.13.1 for kernel 4.18.0-425.19.2.el8_7.x86_64 (x86_64)
Tue May  9 13:51:15 UTC 2023
make KBUILD_VERBOSE=1 M=/var/lib/dkms/evdi/1.13.1/build SUBDIRS=/var/lib/dkms/evdi/1.13.1/build SRCROOT=/var/lib/dkms/evdi/1.13.1/build CONFIG_MODULE_SIG= -C /lib/modules/4.18.0-425.19.2.el8_7.x86_64/build modules
make[1]: Entering directory '/usr/src/kernels/4.18.0-425.19.2.el8_7.x86_64'
test -e include/generated/autoconf.h -a -e include/config/auto.conf || (		\
echo >&2;							\
echo >&2 "  ERROR: Kernel configuration is invalid.";		\
echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";	\
echo >&2 ;							\
/bin/false)
mkdir -p /var/lib/dkms/evdi/1.13.1/build/.tmp_versions ; rm -f /var/lib/dkms/evdi/1.13.1/build/.tmp_versions/*
make -f ./scripts/Makefile.build obj=/var/lib/dkms/evdi/1.13.1/build
(cat /dev/null;   echo kernel//var/lib/dkms/evdi/1.13.1/build/evdi.ko;) > /var/lib/dkms/evdi/1.13.1/build/modules.order
  gcc -Wp,-MD,/var/lib/dkms/evdi/1.13.1/build/.evdi_platform_drv.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-redhat-linux/8/include -I./arch/x86/include -I./arch/x86/include/generated   -I./include/drm-backport -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -DCC_HAVE_ASM_GOTO -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -DCONFIG_TPAUSE=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -mindirect-branch-cs-prefix -mfunction-return=thunk-extern -fno-jump-tables -fno-delete-null-pointer-checks -Wno-frame-address -Wno-format-truncation -Wno-format-overflow -Wno-int-in-bool-context -O2 --param=allow-store-data-races=0 -Wframe-larger-than=2048 -fstack-protector-strong -Wno-unused-but-set-variable -Wno-unused-const-variable -g -gdwarf-4 -pg -mrecord-mcount -mfentry -DCC_USING_FENTRY -fno-inline-functions-called-once -Wdeclaration-after-statement -Wno-pointer-sign -Wno-stringop-truncation -Wno-maybe-uninitialized -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -fmacro-prefix-map=./= -Wno-packed-not-aligned -Iinclude/uapi/drm -Iinclude/drm -DEL8  -DMODULE  -DKBUILD_BASENAME='"evdi_platform_drv"' -DKBUILD_MODNAME='"evdi"' -c -o /var/lib/dkms/evdi/1.13.1/build/.tmp_evdi_platform_drv.o /var/lib/dkms/evdi/1.13.1/build/evdi_platform_drv.c
   ./tools/objtool/objtool orc generate  --rethunk  --module --no-fp  --retpoline "/var/lib/dkms/evdi/1.13.1/build/.tmp_evdi_platform_drv.o";
  gcc -Wp,-MD,/var/lib/dkms/evdi/1.13.1/build/.evdi_platform_dev.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-redhat-linux/8/include -I./arch/x86/include -I./arch/x86/include/generated   -I./include/drm-backport -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -DCC_HAVE_ASM_GOTO -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -DCONFIG_TPAUSE=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -mindirect-branch-cs-prefix -mfunction-return=thunk-extern -fno-jump-tables -fno-delete-null-pointer-checks -Wno-frame-address -Wno-format-truncation -Wno-format-overflow -Wno-int-in-bool-context -O2 --param=allow-store-data-races=0 -Wframe-larger-than=2048 -fstack-protector-strong -Wno-unused-but-set-variable -Wno-unused-const-variable -g -gdwarf-4 -pg -mrecord-mcount -mfentry -DCC_USING_FENTRY -fno-inline-functions-called-once -Wdeclaration-after-statement -Wno-pointer-sign -Wno-stringop-truncation -Wno-maybe-uninitialized -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -fmacro-prefix-map=./= -Wno-packed-not-aligned -Iinclude/uapi/drm -Iinclude/drm -DEL8  -DMODULE  -DKBUILD_BASENAME='"evdi_platform_dev"' -DKBUILD_MODNAME='"evdi"' -c -o /var/lib/dkms/evdi/1.13.1/build/.tmp_evdi_platform_dev.o /var/lib/dkms/evdi/1.13.1/build/evdi_platform_dev.c
In file included from /var/lib/dkms/evdi/1.13.1/build/evdi_platform_dev.c:27:
/var/lib/dkms/evdi/1.13.1/build/evdi_drm_drv.h:32:10: fatal error: drm/drm_irq.h: No such file or directory
 #include <drm/drm_irq.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:318: /var/lib/dkms/evdi/1.13.1/build/evdi_platform_dev.o] Error 1
make[1]: *** [Makefile:1585: _module_/var/lib/dkms/evdi/1.13.1/build] Error 2
make[1]: Leaving directory '/usr/src/kernels/4.18.0-425.19.2.el8_7.x86_64'
make: *** [Makefile:38: all] Error 2
[root@localhost ~]# 

```
  

I removed the evdi_drm_drv.h includes from  the code and then used dkms to build and install the module:

```
cd /usr/src/evdi-1.13.1/
sed 's@#include <drm/drm_irq.h>@@' evdi_drm_drv.h -i
dkms build -m evdi -v 1.13.1
dkms install -m evdi -v 1.13.1

```
And this seems to have solved being able to build and install it *( though I'm away from a dock right now so can't properly retest it's functionality)

**Comment by zlig** [comment] 2023-06-24 15:16
Thanks @mark-hyde for providing the details of the issue and the resolution, I confirm the same steps worked for me to resolve the problem and install DisplayLink 1.13.1 on RHEL 8.7 (4.18.0-425.19.2.el8_7.x86_64):

```
# Install DisplayLink 1.13.1 (but the  service fails to start)
dnf install rocky-8-displaylink-1.13.1-1.x86_64.rpm

# Patch the local sources for EVDI, rebuild and load the module
cd /usr/src/evdi-1.13.1/
sed 's@#include <drm/drm_irq.h>@@' evdi_drm_drv.h -i
dkms build -m evdi -v 1.13.1
dkms install -m evdi -v 1.13.1

# Check the status of the module and the service
modprobe evdi
systemctl status displaylink-driver.service
```

**Comment by elguero** [comment] 2023-06-24 20:46
Hi.  This patch should have fixed this issue: 8e6527a670e97c919b026e35ebadbf83018f51c7

I should have pushed a new release to include that patch.  Doing that right now.

**Comment by zlig** [comment] 2023-06-25 12:23
> Hi. This patch should have fixed this issue: [8e6527a](https://github.com/displaylink-rpm/displaylink-rpm/commit/8e6527a670e97c919b026e35ebadbf83018f51c7)

Thank you @elguero ! Looks like the problem is fixed in *rocky-8-displaylink-1.13.1-2.x86_64.rpm*

I uninstalled the previous version, removed the folder `/usr/src/evdi-1.13.1` which contains the sources previously patched manuallly, install the newest version with `sudo dnf install rocky-8-displaylink-1.13.1-2.x86_64.rpm`, and the DisplayLink driver now works find with the dual monitors of the docking station (ThinkPad Hybrid USB-C).

**Comment by elguero** [comment] 2023-06-25 12:27
@zlig Awesome!  Thank you for trying it out and the feedback that it works.

**Closed** 2023-06-25 12:28 UTC
Labels: Bug

**Comment by mark-hyde** [comment] 2023-06-27 09:36
Thank you for resolving this @elguero, I very much appreciate all the work you do on this project.

**Comment by mark-hyde** [comment] 2023-06-27 09:39
I've installed the updated package but cannot yet confirm that it works as I only use a DisplayPort dock when I visit the office (which is likely to be next week).
