### ISSUE TITLE
Kernel 4.20?

### ISSUE THREAD

**Issue by elegos** [displaylink-rpm/displaylink-rpm#78] opened 2019-01-23 11:25 UTC
Hello!

My friends in the office using kernel 4.20 under Ubuntu have some troubles compiling the evdi for the written kernel version, as it seems that some functions have been deleted or renamed.

I see that Fedora 29 is proposing me kernel version 4.20.3-200, and I'm wondering if I'll have any issue after the installation.

May you please confirm me it's still working as expected?

Thanks :)

**Comment by stdweird** [comment] 2019-01-23 21:22
@elegos just installed f29, using 4.20, and dkms fails due to build falures in evdi:
```
s.o /var/lib/dkms/evdi/1.5.1/build/evdi_stats.c
/var/lib/dkms/evdi/1.5.1/build/evdi_fb.c: In function ‘evdifb_create’:
/var/lib/dkms/evdi/1.5.1/build/evdi_fb.c:370:33: error: ‘FBINFO_CAN_FORCE_OUTPUT’ undeclared (first use in this function)
  info->flags = FBINFO_DEFAULT | FBINFO_CAN_FORCE_OUTPUT;
                                 ^~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/evdi/1.5.1/build/evdi_fb.c:370:33: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [scripts/Makefile.build:291: /var/lib/dkms/evdi/1.5.1/build/evdi_fb.o] Error 1
make[2]: *** Waiting for unfinished jobs....
   ./tools/objtool/objtool orc generate  --module --no-fp --retpoline "/var/lib/dkms/evdi/1.5.1/build/evdi_encoder.o";
   ./tools/objtool/objtool orc generate  --module --no-fp --retpoline "/var/lib/dkms/evdi/1.5.1/build/evdi_main.o";
   ./tools/objtool/objtool orc generate  --module --no-fp --retpoline "/var/lib/dkms/evdi/1.5.1/build/evdi_stats.o";
   ./tools/objtool/objtool orc generate  --module --no-fp --retpoline "/var/lib/dkms/evdi/1.5.1/build/evdi_connector.o";
   ./tools/objtool/objtool orc generate  --module --no-fp --retpoline "/var/lib/dkms/evdi/1.5.1/build/evdi_drv.o";
   ./tools/objtool/objtool orc generate  --module --no-fp --retpoline "/var/lib/dkms/evdi/1.5.1/build/evdi_modeset.o";
   ./tools/objtool/objtool orc generate  --module --no-fp --retpoline "/var/lib/dkms/evdi/1.5.1/build/evdi_gem.o";
make[1]: *** [Makefile:1567: _module_/var/lib/dkms/evdi/1.5.1/build] Error 2
make[1]: Leaving directory '/usr/src/kernels/4.20.3-200.fc29.x86_64'
make: *** [Makefile:22: all] Error 2

```

i tried to look for anything related, but no solution so far

**Comment by stdweird** [comment] 2019-01-23 21:33
and ofcourse, after you paste stuff like this, next thing you find the solution...

https://github.com/DisplayLink/evdi/pull/148
apply it to /usr/src/evdi-1.5.1/evdi_fb.c and run `/sbin/dkms install evdi/1.5.1 >> /var/log/displaylink/displaylink.log 2>&1`

**Comment by elegos** [comment] 2019-01-23 22:12
Awesome! Thank you very much :)

**Comment by csilva235** [comment] 2019-01-25 02:52
> and ofcourse, after you paste stuff like this, next thing you find the solution...
> 
> [DisplayLink/evdi#148](https://github.com/DisplayLink/evdi/pull/148)
> apply it to /usr/src/evdi-1.5.1/evdi_fb.c and run `/sbin/dkms install evdi/1.5.1 >> /var/log/displaylink/displaylink.log 2>&1`

I'm having a bit of trouble understanding how to do this. 

Could you elaborate on how to get this working?

**Comment by elegos** [comment] 2019-01-25 08:53
@csilva235 open the linked pull request, click on the "Files changed" tab and apply the modification on your source code (it should be where @stdweird wrote).

**Comment by csilva235** [comment] 2019-01-25 17:49
> @csilva235 open the linked pull request, click on the "Files changed" tab and apply the modification on your source code (it should be where @stdweird wrote).

After I let my brain rest from troubleshooting and rekicking my system earlier in the day, I had a shocking realization that I know how to read and follow very simple instructions. But of course, only after I had already commented asking for clarification. 

The fix has been applied and it's working once again.

**Comment by sorvani** [comment] 2019-01-28 18:02
I did this to resolve 4.20 not working.
https://github.com/DisplayLink/evdi/issues/145

**Comment by ssaavedra** [comment] 2019-01-29 09:15
If you can contribute the time to create a patch in the specfile, we can have a version working for Fedora 29 with Linux 4.20 even before evdi releases officially. Otherwise, we can bump the evdi version when they release.
According to https://github.com/DisplayLink/evdi/pull/142#issuecomment-456773100 a new release is in the works.

**Comment by ssaavedra** [comment] 2019-01-29 09:16
Since this is only applicable to Linux >= 4.20, please use an `#if/#else` preprocessor directive instead of directly patching the line, or the new release will not be compatible with older kernels.

**Comment by jjtt** [comment] 2019-01-30 07:01
This worked for me:

```
--- evdi-1.5.1-orig/evdi_drv.h	2019-01-30 08:57:04.000025423 +0200
+++ evdi-1.5.1/evdi_drv.h	2019-01-30 08:46:21.539286859 +0200
@@ -32,6 +32,10 @@
 #define DRIVER_MINOR      5
 #define DRIVER_PATCHLEVEL 1
 
+#if KERNEL_VERSION(4, 20, 0) <= LINUX_VERSION_CODE
+#define FBINFO_CAN_FORCE_OUTPUT 1
+#endif
+
 struct evdi_fbdev;
 struct evdi_painter;
 struct evdi_flip_queue;
```

**Comment by beshad** [comment] 2019-02-04 21:00
This also worked me
started by running `rpm -q kernel` & `dnf info kernel-headers` to see what other kernels i have. `dnf remove` to uninstall any extra kernels from the list. 
then `sudo dnf clean all && sudo dnf upgrade && reboot`
after all that i managed to do `sudo dkms build evdi/1.5.1 `and the `dkms install`. restarted dkms.service & displaylink.service and got my USB displayworking. I had already followed #78 instructions which seems to be a must. 
my kernel is 4.20.5-200.fc29.x86_64 with exact matching headers, core and modules.

**Comment by InfoSec812** [comment] 2019-02-05 23:01
> This worked for me:
> 
> ```
> --- evdi-1.5.1-orig/evdi_drv.h	2019-01-30 08:57:04.000025423 +0200
> +++ evdi-1.5.1/evdi_drv.h	2019-01-30 08:46:21.539286859 +0200
> @@ -32,6 +32,10 @@
>  #define DRIVER_MINOR      5
>  #define DRIVER_PATCHLEVEL 1
>  
> +#if KERNEL_VERSION(4, 20, 0) <= LINUX_VERSION_CODE
> +#define FBINFO_CAN_FORCE_OUTPUT 1
> +#endif
> +
>  struct evdi_fbdev;
>  struct evdi_painter;
>  struct evdi_flip_queue;
> ```

This worked for me perfectly!

**Comment by ssaavedra** [comment] 2019-02-06 14:49
**You should not redefine the flag** that was removed from the kernel `#define FBINFO_CAN_FORCE_OUTPUT 1`. Instead, you should remove it from **usage**, like in the PR for evdi: https://github.com/DisplayLink/evdi/pull/148/files

Like this:

```
--- evdi-1.5.1-orig/evdi_drv.h	2019-02-06 08:00:04.000025423 +0200
+++ evdi-1.5.1/evdi_drv.h	2019-02-06 08:00:21.539286859 +0200
@@ -367,7 +367,7 @@ static int evdifb_create(struct drm_fb_helper *helper,
 	info->fix.smem_len = size;
 	info->fix.smem_start = (unsigned long)ufbdev->ufb.obj->vmapping;
-	info->flags = FBINFO_DEFAULT | FBINFO_CAN_FORCE_OUTPUT;
+	#if KERNEL_VERSION(4, 20, 0) <= LINUX_VERSION_CODE
+	info->flags = FBINFO_DEFAULT;
+	#else
+	info->flags = FBINFO_DEFAULT | FBINFO_CAN_FORCE_OUTPUT;
+	#endif
 	info->fbops = &evdifb_ops;
```

**Comment by gbraad** [comment] 2019-02-12 23:12
https://github.com/DisplayLink/evdi/pull/148#issuecomment-456773560

**Comment by displaylink-dkurek** [comment] 2019-02-19 12:54
Hi guys, just wanted to let you know updated evdi is live. 
It includes support for 4.20 kernel. To use it please also update
your DisplayLinkManager, which can be downloaded from here:
https://www.displaylink.com/downloads/ubuntu
Cheers!

**Comment by gbraad** [comment] 2019-02-19 14:32
As mentioned elsewhere (https://github.com/DisplayLink/evdi/issues/145#issuecomment-465115436) this will not support kernels < v4.2

**Comment by displaylink-dkurek** [comment] 2019-02-19 14:47
Yes, we are shifting towards 'atomic modeset', which means we are dropping
support for kernels older than 4.2.

**Comment by ssaavedra** [comment] 2019-02-19 16:11
Thanks @displaylink-dkurek for the update. I didn't know you guys at DisplayLink knew about this repo.

If you want to contribute to the RPM packaging (officially or unofficially), please reach out, your PRs are welcome!

Even if you don't develop your own deliverables in the open, there's nothing holding you back from contributing here, and the Fedora community would appreciate getting DisplayLink-enabled devices working too ;-)

**Comment by ssaavedra** [comment] 2019-02-20 12:41
Everything should now be in place. The checklist (#83) is now complete. Travis has just finished building the RPMs that should support Linux 4.20, please check them out at https://github.com/displaylink-rpm/displaylink-rpm/releases/tag/v5.1.26

I'm closing this issue since it was related to an upstream problem, and the last version should have addressed the root cause.

Thanks everyone for the provided ideas and troubleshooting.

**Closed by ssaavedra** 2019-02-20 12:41 UTC
Labels: problem-upstream
