### ISSUE TITLE
after install displaylink.service complain that modprobe evdi  status=1/FAILURE)

### ISSUE THREAD

**Issue by guitarjhk** [displaylink-rpm/displaylink-rpm#46] opened 2017-11-21 13:59 UTC
Used the "displaylink-rpm" - zip download - unpack - cd displaylink-rpm-master - run ./ci/fedora.sh no error - excep for the:
 Loaded: loaded (/usr/lib/systemd/system/displaylink.service; static; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2017-11-21 14:48:59 CET; 3s ago
  Process: 24912 ExecStartPre=/sbin/modprobe evdi (code=exited, status=1/FAILURE)

if looking at the "https://github.com/displaylink-rpm/displaylink-rpm" it say:
The package includes the Open Source evdi library. 

any suggestions 

thanks in advance 

John

**Comment by ffgiff** [comment] 2017-12-29 17:04
Duplicate of https://github.com/displaylink-rpm/displaylink-rpm/issues/48?

**Comment by ssaavedra** [comment] 2018-01-19 12:21
Duplicate, we'll keep track on #48 which is more active.

**Closed by ssaavedra** 2018-01-19 12:21 UTC
